# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ee707e04f9db8e57f1d83c22ca058c7af6792262aac06cdd430aac807ef5d0025409a50d86306624a264d9465825d8c412fe1a6d3661e07455776c81b9a5deb

test:
  secret_key_base: 12878128c065c98a1bc329d8291006bc3f215d5de538485fec58f2bd1db57b814711480a2eeabda8fc7e977b8992923b8f4f5aedbe5f8441ffc0c38f5a20500d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
